# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Roberta Doyle
email: hello@robertascalabrin.com
description: > # this means to ignore newlines until "baseurl:"
  Denver based full-stack developer who traded the beaches for the mountains. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.com/roscalabrin" # the base hostname & protocol for your site
twitter_username: ro_scalabrin
github_username:  roscalabrin

# Build settings
markdown: kramdown
